package com.example.myDemo.model;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * This class represents a H2 database table and its column structure.
 * Column 1 is named ID and is autogenerated in a serial format.
 * Column 2 contains the operation expression.
 * Column 3 contain the result of the expression.
 * Database can be queired to get the desired data.
 */
@Entity
@Table(name = "calculations")
public class Calculation {

    @Id
    @Column(name = "ID")
    @GeneratedValue
    private Long id; //primary key and autogenerated value

    private String operation;
    private double result;

    // Constructors
    public Calculation() {}

    public Calculation(String operation, double result) {

        this.operation = operation;
        this.result = result;
    }

    // Getter for id
    public Long getId() {
        return id;
    }

    // Setter for id
    public void setId(Long id) {
        this.id = id;
    }

    // Getter for operation
    public String getOperation() {
        return operation;
    }

    // Setter for operation
    public void setOperation(String operation) {
        this.operation = operation;
    }

    // Getter for result
    public double getResult() {
        return result;
    }

    // Setter for result
    public void setResult(double result) {
        this.result = result;
    }

    // toString method
    @Override
    public String toString() {
        return "Calculation{" +
                "id=" + id +
                ", operation='" + operation + '\'' +
                ", result=" + result +
                '}';
    }
}
