package com.example.myDemo.model;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "calculations")
public class Calculation {

    @Id
    @Column(name = "ID")
    @GeneratedValue
    private Long id; //primary key and autogenerated value

    private double operand1;
    private double operand2;
    private double result;

    // Constructors
    public Calculation() {}

    public Calculation(double operand1, double operand2, double result) {

        this.operand1 = operand1;
        this.operand2 = operand2;
        this.result = result;
    }

    // Getter for id
    public Long getId() {
        return id;
    }

    // Setter for id
    public void setId(Long id) {
        this.id = id;
    }

    // Getter for operand1
    public double getOperand1() {
        return operand1;
    }

    // Setter for operand1
    public void setOperand1(double operand1) {
        this.operand1 = operand1;
    }

    // Getter for operand2
    public double getOperand2() {
        return operand2;
    }

    // Setter for operand2
    public void setOperand2(double operand2) {
        this.operand2 = operand2;
    }

    // Getter for result
    public double getResult() {
        return result;
    }

    // Setter for result
    public void setResult(double result) {
        this.result = result;
    }
}
